print ('DESENVOLVIDO POR PEDROCANTAO')
print ('CRMA - CARTÃO REGISTRO DE MAQUINÁRIOS AGRÍCOLAS')
print('MAQUINÁRIO:')
marca = input('Qual a marca do seu maquinário ? ')
cor = input('Qual a cor do seu maquinário ? ')
ano = input('Qual o ano do seu maquinário ? ')
nota = input('N° de nota fiscal : ')
bloco = input('N° de registro onde se encontra no bloco do maquinário : ')
print ('PROPRIETÁRIO:')
nome = input('Qual o nome do proprietário ? ')
rg = input('Informe o RG do proprietário : ')
cpf = input('Informe o CPF do proprietário : ')
contato = input('Informe seu número de telefone com DDD : ')
endereço = input('Nos informe seu endereço : ')
print ('SUAS INFORMAÇÕES SOBRE O MAQUINÁRIO :')
print ('MARCA:{}'.format(marca) )
print ('COR:{} '.format(cor))
print ('ANO:{} '.format(ano))
print('N° NOTA FISCAL:{} '.format(nota))
print ('BLOCO:{} '.format(bloco))
print ('AS INFORMAÇÕES DO PROPRIETÁRIO:')
print ('NOME:{} '.format(nome))
print ('RG:{} '.format(rg))
print ('CPF:{} '.format(cpf))
print ('CONTATO:{}'.format(contato))
print('ENDEREÇO:{} '.format(endereço))