import math
print ('DESENVOLVIDO POR PEDROCANTAO')
print ('ACHANDO O SENO, COSSENO E TANGENTE DO ÂNGULO DESEJADO . ')
angulo = float(input('Digite o Ângulo que você deseja : '))
seno = math.sin(math.radians(angulo))
cosseno = math.cos(math.radians(angulo))
tangente = math.tan(math.radians(angulo))
print ('O ângulo de {} tem o SENO de {:.2f} ' .format(angulo, seno))
print ('O ângulo de {} tem o COSSENO de {:.2f} ' .format(angulo, cosseno))
print ('O ângulo de {} tem a TANGENTE de {:.2f} '.format(angulo, tangente))