print ('Nome : Pedro Lucas Rodrigues Cantão')
print ('Nome do APP : GPET')
print('Disciplina : Análise e Desenvolvimento de Sistemas')
print('Aplicativo desenvolvido para saber onde seu pet está . ')
latitude = input ('Qual latitude você está ? ')
longitude = input ('Qual longitude você está ?')
lapet = input ('Qual latitude seu pet está ? ')
lopet = input ('Qual longitude seu pet está ? ')
print ('A latitude que você está é {} '.format(latitude))
print ('A longitude que você está é {} '.format(longitude))
print('A latitude em que seu pet está é, {} '.format(lapet))
print('A longitude em que seu pet está é, {} '.format(lopet))
#print (int(longitude)-int(lopet))
resultado1 = (int(longitude)-int(lopet))
resultado2 = (int(latitude)-int(lapet))
resultado3 = int(resultado1)+int(resultado2) / 2
print ('a longitude do seu pet de vc é de : {} metros.'.format(resultado3))